#### ***Numpy For Data Science***

In [1]:
import numpy as np 
arr = np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


- ***Numpy Creation***

In [2]:
# from list 
arr = np.array([1,2,3,"AIML","DS"])
print(arr,type(arr))

['1' '2' '3' 'AIML' 'DS'] <class 'numpy.ndarray'>


In [3]:
# From 2D Matrix
arr = np.array([[1,2,3,4,5],[7,8,9,10,12]])
print(arr,arr.shape)

[[ 1  2  3  4  5]
 [ 7  8  9 10 12]] (2, 5)


In [5]:
# From 3D Matrix 
arr = np.array([[1,2,3],[4,5,6],[6,7,8]])
print(arr,arr.shape)

[[1 2 3]
 [4 5 6]
 [6 7 8]] (3, 3)


- ***Numpy Inbuilt Operations***

In [6]:
arr = np.zeros((3,4))
print(arr,arr.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4)


In [7]:
arr = np.ones((2,2))
print(arr,arr.shape)

[[1. 1.]
 [1. 1.]] (2, 2)


In [8]:
arr = np.full((3,3),8)
print(arr,arr.shape)

[[8 8 8]
 [8 8 8]
 [8 8 8]] (3, 3)


In [10]:
arr = np.eye(3)
print(arr,arr.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)


In [11]:
# generating random number series 
arr = np.arange(1,20,3)
print(arr)

[ 1  4  7 10 13 16 19]


In [17]:
arr = np.linspace(1,10,7)
print(arr)

[ 1.   2.5  4.   5.5  7.   8.5 10. ]


In [18]:
## Arrays Properties
arr = np.array([[1,2,3],
               [3,4,5],[7,8,9]])

print(arr.shape) # dimensions - (m x n)
print(arr.size) # total elements - m*n
print(arr.ndim) # dimension
print(arr.dtype) # data type object

(3, 3)
9
2
int64


In [19]:
# Changing Datatype 
str_ar = np.array([1,2,3],dtype="U")
print(str_ar,str_ar.dtype)

['1' '2' '3'] <U1


In [20]:
float_ar = np.array([1,2,3,4],dtype="float64")
print(float_ar,float_ar.dtype)

[1. 2. 3. 4.] float64


In [21]:
int_ar = float_ar.astype(np.int32)
print(int_ar,int_ar.dtype)

[1 2 3 4] int32


In [22]:
float_ar = int_ar.astype(np.float64)
print(float_ar,float_ar.dtype)

[1. 2. 3. 4.] float64


In [26]:
# Array Reshaping 
ar = np.array([1,2,3,4,5,6])
print(ar.shape)

# convert 1D --> 2D
reshaped = ar.reshape((3,2))
print(reshaped,reshaped.shape)

# convert 2D --> 1D
flatten = reshaped.flatten()
print(flatten,flatten.shape)

(6,)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [27]:
## Indexing
arr = np.array([1,2,3,4,5,7])
print(arr[2])
print(arr[0])

3
1


In [28]:
## 2D Aray Indexing
arr = np.array([[1,2,3],[4,5,7],[2,8,9]])
print(arr[0][1])
print(arr[1][2])

2
7


In [29]:
## Fancy Indexing
arr = np.array([1,2,3,4,5,7])
idx = [0,2,4]
print(arr[idx])

[1 3 5]


In [30]:
## Boolean Indexing
print(arr[arr > 2])
print(arr[arr%2 == 0])

[3 4 5 7]
[2 4]


In [31]:
arr = np.array([[1,3,2],[4,5,7],[8,9,10]])
print(arr)
print(np.sum(arr))

col_sum = np.sum(arr,axis=0)
print(col_sum)

row_sum = np.sum(arr,axis=1)
print(row_sum)

[[ 1  3  2]
 [ 4  5  7]
 [ 8  9 10]]
49
[13 17 19]
[ 6 16 27]


- ravel( ) → Returns a view (if possible), faster, changes may affect the original array.

- flatten() → Returns a copy, changes do not affect the original array.

In [32]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d.ravel())
print(arr_2d.flatten())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [33]:
arr_2d[0][2] = 7
print(arr_2d.ravel())
print(arr_2d.flatten())

[1 2 7 4 5 6]
[1 2 7 4 5 6]


In [34]:
print(arr_2d)

[[1 2 7]
 [4 5 6]]


In [35]:
## Common Datatype
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([1.0,2.0,5.0,7.0])
ar3 = np.array(["Python","DS","AIML"])

print(ar1.dtype)
print(ar2.dtype)
print(ar3.dtype)
print(ar1.nbytes)

int64
float64
<U6
40


In [36]:
##  Complex Numbers
arr1 = np.array([2 + 3j])
arr2 = np.array([5 + 8j])
print(arr1, arr1.dtype)

[2.+3.j] complex128


In [37]:
print(arr1+arr2)
print(arr1-arr2)

[7.+11.j]
[-3.-5.j]


In [38]:
## Vectorization
arr = np.array([1, 2, 3, 4, 5])

sq_arr = arr ** 2       
print(sq_arr)

arr2 = np.array([6, 7, 8, 9, 10])
print(arr + arr2)      

[ 1  4  9 16 25]
[ 7  9 11 13 15]


In [39]:
#Broadcasting
arr_mul10 = arr * 10  
print(arr_mul10)

arr1D = np.array([1, 2, 3])
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1D + arr2D)

[10 20 30 40 50]
[[2 4 6]
 [5 7 9]]


In [40]:
## Vector Normalization
arr = np.array([[1,2,3],[4,5,7]])
mean = np.mean(arr)
std_dv = np.std(arr)

print((arr-mean)/std_dv)

[[-1.35224681 -0.84515425 -0.3380617 ]
 [ 0.16903085  0.6761234   1.69030851]]


In [41]:
## Mathematical Functions
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))     
print(np.prod(arr))    
print(np.min(arr))    
print(np.argmin(arr))  
print(np.max(arr))     
print(np.argmax(arr))  
print(np.mean(arr))    
print(np.median(arr))  
print(np.std(arr))     
print(np.var(arr)) 

15
120
1
0
5
4
3.0
3.0
1.4142135623730951
2.0


In [42]:
arr = np.array([1,2,3,4,5,7])
print(np.square(arr))   
print(np.sqrt(arr))     
print(np.pow(arr, 3))

[ 1  4  9 16 25 49]
[1.         1.41421356 1.73205081 2.         2.23606798 2.64575131]
[  1   8  27  64 125 343]


In [43]:
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.94591015]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.84509804]
[0.         1.         1.5849625  2.         2.32192809 2.80735492]
[   2.71828183    7.3890561    20.08553692   54.59815003  148.4131591
 1096.63315843]


In [44]:
print(np.round(2.678))    
print(np.floor(2.678))    
print(np.ceil(2.678))     
print(np.trunc(2.678))

3.0
2.0
3.0
2.0


In [45]:
arr = np.array([1, 2, -5, 3, 8, -4, 2, 5])

print(np.abs(arr))     
print(np.sort(arr))  
print(np.unique(arr))

[1 2 5 3 8 4 2 5]
[-5 -4  1  2  2  3  5  8]
[-5 -4  1  2  3  5  8]


In [46]:
# Vertical Stacking --> row wise & Horizontal Stacking --> column wise
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([5,6,7,8,9])

vstack = np.vstack((ar1,ar2))
hstack = np.hstack((ar1,ar2))

In [47]:
print(vstack)
print(hstack)

[[1 2 3 4 5]
 [5 6 7 8 9]]
[1 2 3 4 5 5 6 7 8 9]


- ***Handling Missing Values With Numpy***

In [ ]:
arr = np.array([1,2,np.nan,6,9,np.nan])
print(arr)
print(np.isnan(arr))

[ 1.  2. nan  6.  9. nan]
[False False  True False False  True]


In [ ]:
# Numeric Value
cleaned_arr = np.nan_to_num(arr,nan=0)
print(cleaned_arr)

[1. 2. 0. 6. 9. 0.]


In [52]:
# Infinte Value
arr = np.array([1,2,3,np.inf,4,-np.inf,7])
print(arr)
print(np.isinf(arr))

[  1.   2.   3.  inf   4. -inf   7.]
[False False False  True False  True False]


In [53]:
cleaned_arr = np.nan_to_num(arr,posinf=1,neginf=-1)
print(cleaned_arr)

[ 1.  2.  3.  1.  4. -1.  7.]
