#### ***Train Our Perceptron***

In [1]:
import torch  
import torch.nn as nn 

# Inputs 
torch.manual_seed(42)
inputs = torch.tensor([1.2,2.0,3.2])

neuron = nn.Linear(in_features=3,out_features=1)

In [2]:
output = neuron(inputs)
output

tensor([1.5856], grad_fn=<ViewBackward0>)

In [3]:
# Verify Our Neuron 
neuron.weight @ inputs + neuron.bias

tensor([1.5856], grad_fn=<AddBackward0>)

In [4]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)